language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- 3.4
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; alias R="travis_wait
  100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: YHRdtdEVdkTVy1Gy/kDAEcrEUG53KB0y/ryaCFaUx7ZRXYNLT/RNsTkYHBUjrUM3pbRmIMRFrodM49aN/0rYeUUqN9HQLnnv1QDkKX4meiNUPZ0R0X8OMH2WA55vaXeWOpuhTzZmC7KpkulsJOPpLm9Cs0rTCSsgZF2FbWGN/jzVpTGwDUFZDxNQfkLM+MZQDUStivczwKzZzqWRFcm++V+sf2RaCTX5tRJnE9UDzZiZVTbu0htnEQLh+Kfo6/TR2zR58JkvXBjNXZjWH8LJbv1R+Bo8q9GRvSixk1cclIEmu1ZYJCAZXtu4R6i3jbaxMTbFNrJVWJrzFjVK4t+M4i+aQZIp5BCH1bHtZu+WDFAplKOMxZrBLJMF+22YrImiZPz8vSnHE4IDyIT0Q4uQbcxrxrwFk4WNtbEz5/bKfymaAo4LUXXt3fkqbr8j4IwGd5/YfpnQBn4IQmLQBjtEfFNHCofBCqN/t25D0u3fPpvWOHWCfm+mgPGvZVNo/w+N5bPxo6BgdBJadhqO2EvXkGB4ket55kYs5qbjhfJOpDnsdJhn4rwsVifRJO62cOL4ETocBcLnbH3J4mBWtS2DPF/j/uTkKohxRFx2TSe9fZu5PJf68XCrgEQWAOvgpfdIeFz2ufV/hsu3BScvUs+HNjeQhvGgs9dljEf1ORvlLZs=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
