language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- 3.4
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; alias R="travis_wait
  100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: eSymbcWeJSQD+lYZ0xU50pLb4qwjP4iJa6ou2Nk/INeJ5iTRQ8nt4rwMUs7bHteL+6lJH7lxWR3pGzMShYcZo8nRTEU4GNV0Vsrp655gHcJMDGyFYVXQCZhco7Hcp0VFDkcKgRnWg9qHxxqT8nlciTETW1Z+jfeWFbgxkDqFEcb18Lt0zVieJwMimevUolxFa/OtV6Ja3UmrlGxykvn8ztMnhasRjlGOKNI5pR2cqccQzDfvVfZnVpYW4Kix6dfT9fUeQ2OC0evoEET4mSWy1aqlWHVJ2hTUsX/OLQEXTkZjCCJu4u0TiZvRmkzorJgTmRInEsOVtBxlAldUmOYEXY5TGG9xW50X2Oi2KAV4k7HcGfVVjbCVvocE6RhtmI8PS7TtJ5iOq5FwmZvM+JnkY6ITsWJu+DWOJ92E1b/UuIa2j5fi3Gy+Wd/ia6ABg02BGO2lRYOwOD0/dX5Kisv048IFX0Kf+m57J+NKUpS2YTBiqLKRZl7PtGaYO8Q9/HrcouazHv4urJrvrMsz8lgDRL7RkOumoc6jVdkU4DPnnH855Jrk+FFput59J2KWMgoe44tAbV+sZSMkCevOZEpyvkLEcLbMY6LB3uom4itukgN4VmltFfFuhEE5Z4SX8bZm1DYglDUYBJ8JJCLk4Wn7bDCp3yS6PG84bn84fCVdQWo=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
